INSERT INTO EMPLOYEE (NAME, DEPARTMENT, SALARY)
VALUES ('Tejal','HR',50000);

INSERT INTO EMPLOYEE (NAME, DEPARTMENT, SALARY)
VALUES ('Aamarapali','Finance',60000);

INSERT INTO EMPLOYEE (NAME, DEPARTMENT, SALARY)
VALUES ('Sayali','IT',70000);
